### ISSUE TITLE
Broken backwards compatibility in 1.2.6

### ISSUE THREAD

**Issue by imaginaris** [pebble8888/ed25519study#11]
In 1.2.6 the minimum required iOS version changed from 11 to 12 and macOS from 10.12 to 10.14.
It's a breaking change so according to semver I'd advise to use 2.0.0 version number instead of 1.2.6.
That way developers using version 1.x.x won't have to pin specific version number in their dependency declaration.

**Comment by pebble8888** [comment]
Try tag 1.2.7. If you have a problem, please send PR. Thank you.

**Comment by imaginaris** [comment]
Ok, I'll stick with 1.2.7, it should work. Thank you.
