### ISSUE TITLE
Version 1.2.7 and 1.2.6 are not available on cocoapods.

### ISSUE THREAD

**Issue by ppamorim** [pebble8888/ed25519study#12]
Hi, these versions are not available on cocoapods. Could you please check this out?

<img width="1144" alt="Screenshot 2021-05-03 at 14 59 00" src="https://user-images.githubusercontent.com/5521682/116885754-27b47180-ac20-11eb-910a-f4237f019d6d.png">

**Comment by pebble8888** [comment]
updated ed25519swift.podspec
Please try 1.2.8

**Comment by pebble8888** [comment]
1.2.6 or higher version is not supported in cocoapods. 
I need more time for the support.
CocoaPods needs high maintenance cost.
Please try SPM.

**Comment by ppamorim** [comment]
I can't because it's being used inside another Cocoapods dependency.

**Comment by pebble8888** [comment]
Check it.

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  ed25519swift (1.2.8) successfully published
 📅  May 4th, 09:22
 🌎  https://cocoapods.org/pods/ed25519swift
 👍  Tell your friends!
--------------------------------------------------------------------------------
