### ISSUE TITLE
Ed25519macOSTests.swift copy to iOS run test crash.

### ISSUE THREAD

**Issue by SuperY** [pebble8888/ed25519study#4]
static func ge25519_pack(_ r:inout [UInt8] /* 32 */, _ p:ge)
r.count aways 64, but assert is 32, why macOS is ok, but iOS error..

**Comment by pebble8888** [comment]
Check `Build Configuration`(Debug or Release) for Test Scheme.

**Comment by SuperY** [comment]
But why? And it still not works.
