### ISSUE TITLE
Target iOS 11.0 instead of 11.4

### ISSUE THREAD

**Issue by the-pear** [pebble8888/ed25519study#7]
Why not?
[s.ios.deployment_target = "11.4"](https://github.com/pebble8888/ed25519swift/blob/44f7bda09d3c3698cdd3e240dee34c1436b16e75/ed25519swift.podspec#L9)

**Comment by pebble8888** [comment]
Why do you want to change iOS Deployment Target 11.4 to 11.0 ?
I don't want to support 11.0, 11.1, 11.2, 11.3 for maintainability.

**Comment by pebble8888** [comment]
Now target is iOS12.0.
